services:
  bind:
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
    container_name: bind
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
    volumes:
      - ./bind/config:/etc/bind:rw
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    depends_on:
      - lb1_europe
      - lb2_world
    networks:
      cdn_net:
        ipv4_address: 10.30.0.2
    restart: unless-stopped

  lb1_europe:
    image: haproxy:latest
    container_name: lb1_europe
    ports:
      - "80:80"
    volumes:
      - ./haproxy/lb1-europe.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - node1
      - node2
    networks:
      cdn_net:
        ipv4_address: 10.30.0.10
    restart: unless-stopped

  lb2_world:
    image: haproxy:latest
    container_name: lb2_world
    ports:
      - "8080:80"
    volumes:
      - ./haproxy/lb2-world.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - node3
      - node4
    networks:
      cdn_net:
        ipv4_address: 10.30.0.11
    restart: unless-stopped

  node1:
    image: nginx:latest
    container_name: node1
    volumes:
      - ./images:/usr/share/nginx/html:ro
    networks:
      cdn_net:
        ipv4_address: 10.30.0.20
    restart: unless-stopped

  node2:
    image: nginx:latest
    container_name: node2
    volumes:
      - ./images:/usr/share/nginx/html:ro
    networks:
      cdn_net:
        ipv4_address: 10.30.0.21
    restart: unless-stopped

  node3:
    image: nginx:latest
    container_name: node3
    volumes:
      - ./images:/usr/share/nginx/html:ro
    networks:
      cdn_net:
        ipv4_address: 10.30.0.22
    restart: unless-stopped

  node4:
    image: nginx:latest
    container_name: node4
    volumes:
      - ./images:/usr/share/nginx/html:ro
    networks:
      cdn_net:
        ipv4_address: 10.30.0.23
    restart: unless-stopped

  client-world:
    build:
      context: client/.
    container_name: client-world
    dns:
      - 10.30.0.2
    networks:
      cdn_net:
        ipv4_address: 10.30.0.30
    restart: unless-stopped
    command: sleep infinity
    tty: true

  client-europe:
    build:
      context: client/.
    container_name: client-europe
    dns:
      - 10.30.0.2
    networks:
      cdn_net:
        ipv4_address: 10.30.1.23
    restart: unless-stopped
    command: sleep infinity
    tty: true

networks:
  cdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/16